language: node_js
node_js:
- '4'
before_install:
- rm -rf lib/
- npm install
- npm install -g typescript@2.2.2
- tsc
deploy:
  provider: npm
  email: homenet@denwilliams.net
  on:
    tags: true
    repo: denwilliams/homenet-plugin-mqtt
  api_key:
    secure: OHcCTG/8V6nydZwQaxH5OXXNIfwXgF9BCpB+atwdbQZGWdF0V8BS77003uOGuDDsHroq1JgjV8/5xCAnWQfTT//p5Ee5go3Bz194hMrjXdbYyUcDjFKLmpvV6uP9Mxbkcl7reu9GOaP9iY7Je6w88wmTf6yzFYYx5XQcC+kaAzeucq02IpjsRkcTqdUGvNzERZjjYShgKb4kVB949cAORHjWoRE88G6eDr1UBPyAHXYZIMvxXl5Gh4dDtxiCLwHKF4rRyyj6BekRsioBBk9NPe+y8moHSJnCTDwV67VApSB48mMiqLMezyk4mPDtKzUu2+sGlxUV6vfVIm9CD24byl0sGzRwLtGi2QTnTFBcOOipmSZUrt1Zewk8Y5OzMQfymIklFkwNunGa+NRf2A7TlrAn5fnJVMSJ3zRnrGnQeAfFPDwnmD0PNOdTR37x+pAosxd3KZ931sdSgvj6i1AXxFxmTXTB/+4ED/O5reVo/UMOzpuxLwL7E/fvJpTaBCko5Q/pI1nR/njYwzk36ZXzh6JIrltrRBDdbvRwW4AISduAOFPu8mlUCavuxB4VJII5uBATu3TTjSM///VMKRa3Iv0w2FKtZlagOTB6rM3kpVxJGJJ2teftXtvbSv1xLkRpOOBpPevQ6WVBNvmRFIQhybuvTUdQCVFhADeFlvpSPzA=
